source-mounts := "-v ${PWD}:/alto -v ${PWD}/.docker-cache/cargo:/cargo-home -v ${PWD}/.docker-cache/target:/alto/target"
cache-env := "-e CARGO_HOME=/cargo-home"

prepare-docker-cache:
    mkdir -p .docker-cache/cargo .docker-cache/target

build-graviton-image:
    docker buildx bake --progress plain -f deploy/docker-bake.hcl graviton

validator-graviton-binary: build-graviton-image prepare-docker-cache
    docker run --rm {{source-mounts}} {{cache-env}} -e PACKAGE_NAME=alto-validator -e BINARY_NAME=validator -e OUTPUT_NAME=validator alto-validator-builder:graviton-local

indexer-graviton-binary: build-graviton-image prepare-docker-cache
    docker run --rm {{source-mounts}} {{cache-env}} -e PACKAGE_NAME=alto-indexer -e BINARY_NAME=indexer -e OUTPUT_NAME=indexer alto-validator-builder:graviton-local

graviton-binaries: validator-graviton-binary indexer-graviton-binary

build-graviton4-image:
    docker buildx bake --progress plain -f deploy/docker-bake.hcl graviton4

validator-graviton4-binary: build-graviton4-image prepare-docker-cache
    docker run --rm {{source-mounts}} {{cache-env}} -e PACKAGE_NAME=alto-validator -e BINARY_NAME=validator -e OUTPUT_NAME=validator alto-validator-builder:graviton4-local

indexer-graviton4-binary: build-graviton4-image prepare-docker-cache
    docker run --rm {{source-mounts}} {{cache-env}} -e PACKAGE_NAME=alto-indexer -e BINARY_NAME=indexer -e OUTPUT_NAME=indexer alto-validator-builder:graviton4-local

graviton4-binaries: validator-graviton4-binary indexer-graviton4-binary

build-intel-image:
    docker buildx bake --progress plain -f deploy/docker-bake.hcl intel

validator-intel-binary: build-intel-image prepare-docker-cache
    docker run --rm {{source-mounts}} {{cache-env}} -e PACKAGE_NAME=alto-validator -e BINARY_NAME=validator -e OUTPUT_NAME=validator alto-validator-builder:intel-local

indexer-intel-binary: build-intel-image prepare-docker-cache
    docker run --rm {{source-mounts}} {{cache-env}} -e PACKAGE_NAME=alto-indexer -e BINARY_NAME=indexer -e OUTPUT_NAME=indexer alto-validator-builder:intel-local

intel-binaries: validator-intel-binary indexer-intel-binary
